// equipment.js — Database attrezzatura, preset telescopio e sensore
// ============================================================

        function popolaMenuAttrezzatura() {
            const selTel = document.getElementById('preset-telescope'); 
            selTel.innerHTML = '<option value="" data-i18n="select_opt">-- Seleziona --</option>';
            
            let customTels = JSON.parse(localStorage.getItem('ad_custom_telescopes')) || [];
            
            let allTels = [...customTels, ...dbTelescopiBase];
            allTels.forEach(t => { 
                let opt = document.createElement('option'); 
                opt.value = t.focale + ',' + t.diametro; 
                opt.textContent = (customTels.some(ct => ct.nome === t.nome) ? "⭐ " : "") + t.nome; 
                selTel.appendChild(opt); 
            });

            const selCam = document.getElementById('preset-sensor'); 
            selCam.innerHTML = '<option value="" data-i18n="select_opt">-- Seleziona --</option>';
            dbCamereBase.forEach(c => { 
                let opt = document.createElement('option'); 
                opt.value = `${c.w},${c.h},${c.p}`; 
                opt.textContent = c.nome; 
                selCam.appendChild(opt); 
            });
        }

        function applicaPresetTelescopio() { 
            let v = document.getElementById('preset-telescope').value; 
            if(v){ 
                let p = v.split(','); 
                document.getElementById('focal-length').value = p[0]; 
                document.getElementById('aperture').value = p[1] || 100; 
                aggiornaFOV();
                calcolaTempi();
            } 
        }

        function applicaPresetSensore() { 
            let v = document.getElementById('preset-sensor').value; 
            if(v){
                let p=v.split(',');
                document.getElementById('sensor-width').value=p[0];
                document.getElementById('sensor-height').value=p[1];
                if(p[2]) document.getElementById('pixel-size').value=p[2];
                aggiornaFOV();
            } 
        }

        

        // Iniezione traduzioni per il bottone Salva
        i18n.it.save_btn = "💾 Salva";
        i18n.en.save_btn = "💾 Save";
        i18n.es.save_btn = "💾 Guardar";
        i18n.zh.save_btn = "💾 保存";
        i18n.it.aperture = "Diametro (mm):";
        i18n.en.aperture = "Aperture (mm):";
        i18n.es.aperture = "Diámetro (mm):";
        i18n.zh.aperture = "口径 (mm):";

        i18n.it.asiair_close = "✅ Chiudi e Vai al Telescopio";
        i18n.en.asiair_close = "✅ Close and Go to Mount";
        i18n.es.asiair_close = "✅ Cerrar e Ir al Telescopio";
        i18n.zh.asiair_close = "✅ 关闭并开始拍摄";
        i18n.it.export_asiair = "🔴 Esporta per ZWO ASIAIR";
        i18n.en.export_asiair = "🔴 Export ZWO ASIAIR";
        i18n.es.export_asiair = "🔴 Exportar ZWO ASIAIR";
        i18n.zh.export_asiair = "🔴 导出 ZWO ASIAIR";
        i18n.it.info_strat_analysis = "L'analisi è generata da un algoritmo matematico che valuta la tipologia del bersaglio, la magnitudine, il rapporto focale dello strumento, l'inquinamento lunare e le caratteristiche del sensore per stimare il tempo di integrazione ideale.";
        i18n.en.info_strat_analysis = "The analysis is generated by a mathematical algorithm that evaluates the target type, its magnitude, your instrument's focal ratio, lunar pollution, and sensor characteristics to estimate the ideal integration time.";
        i18n.es.info_strat_analysis = "El análisis es generado por un algoritmo matemático que evalúa el tipo de objetivo, la magnitud, la relación focal del instrumento, la contaminación lunar y las características del sensor para estimar el tiempo ideal de integración.";
        i18n.zh.info_strat_analysis = "该分析由数学算法生成，综合评估目标类型、星等、仪器的焦比、月光污染以及传感器特性，从而估算出理想的曝光时间。";
        i18n.it.rotation = "Rotazione:";
        i18n.en.rotation = "Rotation (PA):";
        i18n.es.rotation = "Rotación (PA):";
        i18n.zh.rotation = "相机旋转 (PA):";
        i18n.it.pixel_size = "Pixel (µm):";
        i18n.en.pixel_size = "Pixel (µm):";
        i18n.es.pixel_size = "Pixel (µm):";
        i18n.zh.pixel_size = "像素 (µm):";

        i18n.it.sampling_scale = "Scala di Campionamento";
        i18n.en.sampling_scale = "Image Scale (Sampling)";
        i18n.es.sampling_scale = "Escala de Muestreo";
        i18n.zh.sampling_scale = "采样率 (Image Scale)";

        i18n.it.oversampled = "⚠️ Sovracampionato (Luce dispersa, minor SNR)";
        i18n.en.oversampled = "⚠️ Oversampled (Light spread, lower SNR)";
        i18n.es.oversampled = "⚠️ Sobremuestreado (Pérdida de luz/SNR)";
        i18n.zh.oversampled = "⚠️ 过采样 (星点模糊, 信噪比低)";

        i18n.it.ideal_sampling = "✅ Campionamento Ideale";
        i18n.en.ideal_sampling = "✅ Ideal Sampling";
        i18n.es.ideal_sampling = "✅ Muestreo Ideal";
        i18n.zh.ideal_sampling = "✅ 理想采样";

        i18n.it.undersampled = "⚠️ Sottocampionato (Stelle squadrate)";
        i18n.en.undersampled = "⚠️ Undersampled (Blocky stars)";
        i18n.es.undersampled = "⚠️ Submuestreado (Estrellas cuadradas)";
        i18n.zh.undersampled = "⚠️ 欠采样 (星点呈方形)";
        i18n.it.rotate_target = "Ruota Camera (Rotatore Auto)";
        i18n.en.rotate_target = "Rotate Camera (Auto Rotator)";
        i18n.es.rotate_target = "Rotar Cámara (Rotador Auto)";
        i18n.zh.rotate_target = "旋转相机 (自动旋转器)";

        function salvaTelescopioCustom() {
            let f = document.getElementById('focal-length').value;
            let d = document.getElementById('aperture').value;
            
            // Traduzione dinamica dell'errore
            let errTxt = lang === 'it' ? "Inserisci prima una Focale e un Diametro validi nei campi sottostanti." : 
                         lang === 'en' ? "Please enter a valid Focal Length and Aperture in the fields below." : 
                         lang === 'es' ? "Ingresa primero una Focal y Diámetro válidos en los campos de abajo." : 
                                         "请先在下方输入有效的焦距和口径。";
            
            if(!f || !d || isNaN(f) || isNaN(d)) { alert(errTxt); return; }
            
            // Traduzione dinamica della richiesta del nome
            let pTxt = lang === 'it' ? `Setup: Focale ${f}mm, Diametro ${d}mm.\nInserisci il NOME del Telescopio/Obiettivo:` : 
                       lang === 'en' ? `Setup: Focal ${f}mm, Aperture ${d}mm.\nEnter the NAME of your Telescope/Lens:` : 
                       lang === 'es' ? `Equipo: Focal ${f}mm, Diámetro ${d}mm.\nIngresa el NOMBRE del Telescopio/Lente:` : 
                                       `当前设置: 焦距 ${f}mm, 口径 ${d}mm.\n请输入望远镜/镜头的名称:`;
            
            let nome = prompt(pTxt);
            if(!nome) return;
            
            let customTels = JSON.parse(localStorage.getItem('ad_custom_telescopes')) || [];
            customTels.push({ nome: nome.trim(), focale: parseInt(f), diametro: parseInt(d) });
            localStorage.setItem('ad_custom_telescopes', JSON.stringify(customTels));
            
            popolaMenuAttrezzatura();
            document.getElementById('preset-telescope').value = `${f},${d}`;
        }

        
let latCorrente = 46.062, lonCorrente = 13.235, datiMeteo = null, indicePartenza = 0, chartAltezza = null, targetSelezionato = null, aladinSkyMap = null, vistaPrecedente = 'dashboard-view';
        let fovCenterOverride = null; // {ra: gradi_decimali, dec: gradi_decimali} — null = usa coordinate target
        // Coordinate centro FOV: null = usa quelle originali del target, altrimenti override da drag
        let mappaScura = L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png', { maxZoom: 19, attribution: 'Meteo Data &copy; <a href="https://open-meteo.com/" target="_blank" style="color:#bb86fc;">Open-Meteo</a> | Map &copy; <a href="https://carto.com/" target="_blank">CartoDB</a>' });
        let map = L.map('map', { center: [latCorrente, lonCorrente], zoom: 8, layers: [mappaScura], zoomControl: false });
        L.control.zoom({ position: 'bottomright' }).addTo(map);
        let layers = { basse: L.layerGroup().addTo(map), medie: L.layerGroup(), alte: L.layerGroup(), jet: L.layerGroup(), luna: L.layerGroup(), umidita: L.layerGroup() };
        let marker = L.marker([latCorrente, lonCorrente]).addTo(map).bindPopup("<b>Udine</b>").openPopup();
        let timerRicerca;

        const planetsDatabase = [ { id: "jupiter", name: "jupiter", icon: "🪐", ra: 7.15, dec: 22.8 }, { id: "mars", name: "mars", icon: "🔴", ra: 18.50, dec: -23.5 }, { id: "venus", name: "venus", icon: "✨", ra: 23.50, dec: -3.5 } ];

